language: node_js
node_js:
  - 12

env:
  - NODE_ENV=integration LOG_LEVEL=warn MONGO_URI=127.0.0.1:27017/test_db MONGO_USER=travis MONGO_PASS=test

services:
  - mongodb

before_script:
  - mongo test_db --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

before_deploy:
  - npm run release

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: eu-central-1
  app: mailvelope-key-server
  env: MailvelopeKeyServer-env
  zip_file: release.zip
  bucket_name: elasticbeanstalk-eu-central-1-936909551620
  bucket_path: keyserver
  on:
    repo: mailvelope/keyserver
    branch: master
